/**
 * Style Dictionary v4 — React Native token build
 *
 * Source:  libs/shared/ui/src/tokens/tokens.json  (Tokens Studio format)
 * Output:  libs/shared/ui/src/tokens/*.ts          (TypeScript constants)
 *
 * Flow (design-first):
 *   Figma  →  Tokens Studio plugin exports  →  tokens.json  →  this script  →  *.ts
 *
 * Usage:
 *   node libs/shared/ui/sd.config.mjs
 *   nx run shared-ui:build-tokens
 */

import StyleDictionary from 'style-dictionary';

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Extract hex color from rgba(r,g,b,a) string */
function rgbaToHex(color) {
  const match = color.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);
  if (!match) return color;
  const [, r, g, b] = match;
  return `#${Number(r).toString(16).padStart(2, '0')}${Number(g).toString(16).padStart(2, '0')}${Number(b).toString(16).padStart(2, '0')}`.toUpperCase();
}

/** Extract alpha channel from rgba(r,g,b,a) string */
function rgbaAlpha(color) {
  const match = color.match(/rgba\([^,]+,[^,]+,[^,]+,\s*([^)]+)\)/);
  return match ? parseFloat(match[1]) : 1;
}

/** Auto-generated file header */
const header = `// This file is auto-generated by Style Dictionary.
// Edit libs/shared/ui/src/tokens/tokens.json (via Tokens Studio) — do not edit directly.
`;

// ─── Format: colors ──────────────────────────────────────────────────────────

StyleDictionary.registerFormat({
  name: 'rn/colors',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter(
      (t) => t.path[1] === 'colors',
    );

    const entries = tokens
      .map((t) => `  ${t.path[2]}: '${t.value}',`)
      .join('\n');

    return [
      header,
      `export const colors = {`,
      entries,
      `} as const;`,
      ``,
      `export type ColorToken = keyof typeof colors;`,
      ``,
    ].join('\n');
  },
});

// ─── Format: spacing ─────────────────────────────────────────────────────────

StyleDictionary.registerFormat({
  name: 'rn/spacing',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter(
      (t) => t.path[1] === 'spacing',
    );

    const entries = tokens
      .map((t) => `  ${t.path[2]}: ${Number(t.value)},`)
      .join('\n');

    return [
      header,
      `export const spacing = {`,
      entries,
      `} as const;`,
      ``,
      `export type SpacingToken = keyof typeof spacing;`,
      ``,
    ].join('\n');
  },
});

// ─── Format: radii ───────────────────────────────────────────────────────────

StyleDictionary.registerFormat({
  name: 'rn/radii',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter(
      (t) => t.path[1] === 'borderRadius',
    );

    const entries = tokens
      .map((t) => {
        const comment = t.description ? ` // ${t.description}` : '';
        return `  ${t.path[2]}: ${Number(t.value)},${comment}`;
      })
      .join('\n');

    return [
      header,
      `export const radii = {`,
      entries,
      `} as const;`,
      ``,
      `export type RadiusToken = keyof typeof radii;`,
      ``,
    ].join('\n');
  },
});

// ─── Format: typography ──────────────────────────────────────────────────────

StyleDictionary.registerFormat({
  name: 'rn/typography',
  format: ({ dictionary }) => {
    // Group composite tokens: path could be depth-3 (token itself) or depth-4 (expanded prop).
    // Tokens Studio keeps typography as a single composite token (depth 3).
    const tokens = dictionary.allTokens.filter(
      (t) => t.path[1] === 'typography' && t.path.length === 3,
    );

    const entries = tokens
      .map((t) => {
        const v = t.value;
        const props = [];
        if (v.fontFamily) props.push(`    fontFamily: '${v.fontFamily}',`);
        if (v.fontWeight) props.push(`    fontWeight: '${v.fontWeight}' as const,`);
        if (v.fontSize) props.push(`    fontSize: ${Number(v.fontSize)},`);
        if (v.lineHeight) props.push(`    lineHeight: ${Number(v.lineHeight)},`);
        if (v.letterSpacing) props.push(`    letterSpacing: ${Number(v.letterSpacing)},`);

        const comment = t.description ? `  // ${t.description}\n` : '';
        return `${comment}  ${t.path[2]}: {\n${props.join('\n')}\n  } satisfies TextStyle,`;
      })
      .join('\n\n');

    return [
      header,
      `import { TextStyle } from 'react-native';`,
      ``,
      `export const typography = {`,
      entries,
      `} as const;`,
      ``,
      `export type TypographyToken = keyof typeof typography;`,
      ``,
    ].join('\n');
  },
});

// ─── Format: shadows ─────────────────────────────────────────────────────────
// React Native only supports a single shadow layer.
// We use the outermost (last) layer from Figma's multi-shadow as the base.

StyleDictionary.registerFormat({
  name: 'rn/shadows',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter(
      (t) => t.path[1] === 'boxShadow' && t.path.length === 3,
    );

    const entries = tokens
      .map((t) => {
        const layers = Array.isArray(t.value) ? t.value : [t.value];
        // Use the outermost (largest) shadow layer as the RN base
        const outer = layers[layers.length - 1];

        const shadowColor = outer.color.startsWith('rgba')
          ? rgbaToHex(outer.color)
          : outer.color;
        const opacity = rgbaAlpha(outer.color);
        const blur = Number(outer.blur);
        const y = Math.abs(Number(outer.y));

        const comment = t.description ? `  // ${t.description}\n` : '';
        return [
          `${comment}  ${t.path[2]}: {`,
          `    shadowColor: '${shadowColor}',`,
          `    shadowOffset: { width: 0, height: ${y} },`,
          `    shadowOpacity: ${opacity},`,
          `    shadowRadius: ${blur},`,
          `    elevation: ${Math.round(blur * 0.5)},`,
          `  } satisfies ViewStyle,`,
        ].join('\n');
      })
      .join('\n\n');

    return [
      header,
      `import { ViewStyle } from 'react-native';`,
      ``,
      `// React Native only supports a single shadow layer natively.`,
      `// Values derived from the outermost Figma effect layer.`,
      `export const shadows = {`,
      entries,
      `} as const;`,
      ``,
      `export type ShadowToken = keyof typeof shadows;`,
      ``,
    ].join('\n');
  },
});

// ─── Build ───────────────────────────────────────────────────────────────────

const sd = new StyleDictionary({
  source: ['libs/shared/ui/src/tokens/tokens.json'],
  // Collisions are expected — each formatter intentionally uses only a subset of tokens.
  log: { warnings: 'disabled' },
  platforms: {
    rn: {
      buildPath: 'libs/shared/ui/src/tokens/',
      files: [
        { destination: 'colors.ts', format: 'rn/colors' },
        { destination: 'spacing.ts', format: 'rn/spacing' },
        { destination: 'radii.ts', format: 'rn/radii' },
        { destination: 'typography.ts', format: 'rn/typography' },
        { destination: 'shadows.ts', format: 'rn/shadows' },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log('\n✅ Tokens built successfully.\n');
