// This file is auto-generated by Style Dictionary.
// Edit libs/shared/ui/src/tokens/tokens.json (via Tokens Studio) — do not edit directly.

export const colors = {
  background: '#101D22',
  surface: '#0F172A',
  surfaceOverlay: 'rgba(0, 0, 0, 0.1)',
  input: '#1E293B',
  border: '#334155',
  textPrimary: '#FFFFFF',
  textSecondary: '#E2E8F0',
  textMuted: '#94A3B8',
  textPlaceholder: '#617289',
  brand: '#2BBAED',
} as const;

export type ColorToken = keyof typeof colors;
