// This file is auto-generated by Style Dictionary.
// Edit libs/shared/ui/src/tokens/tokens.json (via Tokens Studio) — do not edit directly.

export const darkColors = {
  background: '#101D22',
  surface: '#0F172A',
  surfaceOverlay: 'rgba(0, 0, 0, 0.1)',
  input: '#1E293B',
  border: '#334155',
  textPrimary: '#FFFFFF',
  textSecondary: '#E2E8F0',
  textMuted: '#94A3B8',
  textPlaceholder: '#617289',
  brand: '#2BBAED',
  error: '#F87171',
} as const;

export const lightColors = {
  background: '#F0F9FF',
  surface: '#FFFFFF',
  surfaceOverlay: 'rgba(0, 0, 0, 0.05)',
  input: '#F1F5F9',
  border: '#CBD5E1',
  textPrimary: '#0F172A',
  textSecondary: '#1E293B',
  textMuted: '#64748B',
  textPlaceholder: '#94A3B8',
  brand: '#2BBAED',
  error: '#DC2626',
} as const;

/** @deprecated Use `useThemeColors()` hook instead. Kept for backwards compat. */
export const colors = darkColors;

export type ColorToken = keyof typeof darkColors;
export type ColorPalette = {
  background: string;
  surface: string;
  surfaceOverlay: string;
  input: string;
  border: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  textPlaceholder: string;
  brand: string;
  error: string;
};
