// This file is auto-generated by Style Dictionary.
// Edit libs/shared/ui/src/tokens/tokens.json (via Tokens Studio) — do not edit directly.

export const radii = {
  sm: 6, // Inputs, buttons
  card: 48, // Cards, modals
} as const;

export type RadiusToken = keyof typeof radii;
