// This file is auto-generated by Style Dictionary.
// Edit libs/shared/ui/src/tokens/tokens.json (via Tokens Studio) — do not edit directly.

import { ViewStyle } from 'react-native';

// React Native only supports a single shadow layer natively.
// Values derived from the outermost Figma effect layer.
export const shadows = {
  // Card container shadow
  card: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.1,
    shadowRadius: 25,
    elevation: 13,
  } satisfies ViewStyle,

  // Brand CTA button glow
  brandGlow: {
    shadowColor: '#2BBAED',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 8,
  } satisfies ViewStyle,
} as const;

export type ShadowToken = keyof typeof shadows;
