// This file is auto-generated by Style Dictionary.
// Edit libs/shared/ui/src/tokens/tokens.json (via Tokens Studio) — do not edit directly.

import { TextStyle } from 'react-native';

export const typography = {
  // Brand name / hero heading
  display: {
    fontFamily: 'Inter',
    fontWeight: '700' as const,
    fontSize: 24,
    lineHeight: 30,
    letterSpacing: -0.6,
  } satisfies TextStyle,

  // Body copy
  body: {
    fontFamily: 'Inter',
    fontWeight: '400' as const,
    fontSize: 16,
    lineHeight: 24,
  } satisfies TextStyle,

  // Input field text and placeholder
  inputText: {
    fontFamily: 'Inter',
    fontWeight: '400' as const,
    fontSize: 16,
    lineHeight: 19,
  } satisfies TextStyle,

  // Form labels, medium emphasis
  label: {
    fontFamily: 'Inter',
    fontWeight: '500' as const,
    fontSize: 14,
    lineHeight: 20,
  } satisfies TextStyle,

  // Helper text, secondary copy
  bodySmall: {
    fontFamily: 'Inter',
    fontWeight: '400' as const,
    fontSize: 14,
    lineHeight: 20,
  } satisfies TextStyle,

  // Inline links
  link: {
    fontFamily: 'Inter',
    fontWeight: '600' as const,
    fontSize: 14,
    lineHeight: 20,
  } satisfies TextStyle,

  // Primary CTA button label
  button: {
    fontFamily: 'Inter',
    fontWeight: '600' as const,
    fontSize: 16,
    lineHeight: 24,
  } satisfies TextStyle,

  // Social / secondary button label
  buttonSecondary: {
    fontFamily: 'Inter',
    fontWeight: '500' as const,
    fontSize: 14,
    lineHeight: 20,
  } satisfies TextStyle,

  // Divider labels, captions
  caption: {
    fontFamily: 'Inter',
    fontWeight: '400' as const,
    fontSize: 12,
    lineHeight: 20,
  } satisfies TextStyle,
} as const;

export type TypographyToken = keyof typeof typography;
